name: Test and Deploy Hexo Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Hexo website repository
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies in the blog directory
      - name: Install dependencies in the blog directory
        working-directory: blog
        run: npm install --force

      # Generate the static website
      - name: Generate Hexo site
        working-directory: blog
        run: npx hexo generate

      # Start the Hexo server in the background
      - name: Start Hexo server
        working-directory: blog
        run: |
          npx hexo server &
          echo $! > hexo.pid  # Save the process ID (PID) to a file

      # Wait for the Hexo server to be available
      - name: Wait for Hexo server to start
        run: npx wait-on http://localhost:4000

      # Clone your Playwright repository
      - name: Clone Playwright repository
        run: |
          git clone https://github.com/vvh24/IS373-Playwright.git playwright-test-repo
          
      # Install Playwright dependencies from the Playwright repo
      - name: Install Playwright dependencies
        working-directory: playwright-test-repo
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright browsers
        working-directory: playwright-test-repo
        run: npx playwright install

      # Run the Playwright tests using the config from the cloned Playwright repository
      - name: Run Playwright tests
        working-directory: playwright-test-repo
        run: npx playwright test --config=playwright.config.js

      # Stop the Hexo server
      - name: Stop Hexo server
        if: always()
        working-directory: blog
        run: |
          if [ -f hexo.pid ]; then
            kill $(cat hexo.pid) || true
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
      # Checkout Hexo repository
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies in the blog directory
      - name: Install dependencies in the blog directory
        working-directory: blog
        run: npm ci

      # Generate Hexo site
      - name: Generate Hexo site
        working-directory: blog
        run: npx hexo generate

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hexo outputs the generated files to the 'public' directory

